# Generated by Django 4.2.14 on 2024-11-05 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_follow_unique_together_alter_follow_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'follower'},
        ),
    ]
